### PR TITLE
Upscale and add SVG versions of some common textures

### PR DESCRIPTION
**Pull request by qwertychouskie**
VRAM usage should still be acceptable, and these high-res versions look a lot better on modern systems (no visible pixelation anymore).

### CODE REVIEW

**Comment by parasti** [comment]
This is cool. Will go over this when I can.

**Comment by ersohnstyne** [comment]
Pro-tip!: Use the surface inspector to update the Texture UV in the NetRadiant. It is better to use!

**Comment by qwertychouskie** [comment]
Cool, thanks!

**Comment by parasti** [comment]
Damn, I messed up.

It's kind of dumb, but due to the way texture coordinates work in .map files, if you change a texture's resolution and simply recompile the .map file, the texture coordinates will not scale to the new resolution. You have to actually open the .map in Radiant and fix it...

I didn't test this before merging, so on my first recompile (just now), goal textures are kind of not in a good place.

I reverted the merge for now. I'll put some time into figuring out a solution that isn't "edit all the .map files", because that's not what I'm about.

**Comment by qwertychouskie** [comment]
Maybe the map compiler could check the expected resolution based on the .map, and the actual resolution, and adjust accordingly?

**Pull request merged**
