### PR TITLE
Emscripten support

### PR DESCRIPTION
**Pull request by parasti**
"What the heck is Emscripten", I hear you ask. It's a toolchain that compiles native code into WebAssembly so you can run it on the web.

I have put up a build of Neverball on https://parasti.github.io/

As far as user experience goes, it's a bit unpolished, but it's a completely solid Neverball experience in the browser. The initial download is around 80 MB, but there is persistent storage, so revisiting the URL should not download everything anew. Your replays and config should also stay put. This thing even runs on a phone, but that needs even more polish before it's on par with anything there. (And, as far as I can tell, it's completely doable.)

### CODE REVIEW

**Comment by rlk** [comment]
This is awesome.

**Comment by qwertychouskie** [comment]
Tried it out, it's awesome!

**Comment by parasti** [comment]
Awesomeness determined, merging.

**Comment by ersohnstyne** [comment]
At least, one of the pull requests has conflicts!
[Check the pull request in the repository!](https://github.com/ersohnstyne/neverball/pull/1)

**Pull request merged**
