### PR TITLE
In-game downloadable level sets

### PR DESCRIPTION
**Pull request by parasti**
Been meaning to do this PR for a long time, but it just turned into one of those things that is never "done".

There's a lot of code here, but not a whole lot of changes to existing code.

This PR implements a download (fetch) API + a basic package management system + extends the set selection screen to show the available packages.

The fetch API needs the `ENABLE_FETCH=curl` flag passed to make, and depends on libcurl. Downloading decidedly happens in a separate thread, so it is not affected by rendering, etc. On Emscripten, the fetch API is always enabled and has no additional dependencies (just the usual async XHR).

All downloads are stored under ~/.neverball/Downloads (Documents\My Games\Neverball\Downloads). On startup, the game downloads a text file with a list of packages available for download. A package can have a name, description and a screenshot. Any missing screenshots are downloaded as well. I reused the set selection screen for showing packages, because the only kind of packages right now are level sets, anyway. To players, they're just downloadable level sets.

Clicking on a downloadable level set initiates a download of the ZIP file of that package. Since the download is multithreaded, you can keep doing whatever in the game - except exit - and the download will keep going in the background. Once done, the ZIP file is added to the virtual filesystem. At that point, the downloadable level set becomes a regular level set.

Packages as well as the manifest text file are created via a couple of shell scripts.

At the moment, the manifest text file, the package files and screenshots are hosted on neverball.github.io. This is just because they need to be there for the Emscripten build anyway (due to CORS).

My original motivation was smaller initial download size for the Emscripten build (it went from 49 MB to 23 MB). I soon realized that with a little effort this could be used to download any level sets that are "published" in the manifest text file, so I made a "Neverball package repository" (https://github.com/Neverball/neverball-packages) and added Reshaun's iLevels collection there (http://neverforum.com/fmpbo/viewtopic.php?id=2793). There's a shell script that looks for a local clone of this repo and creates packages from the directories found within.

I have only tested this on Windows and in the browser (https://neverball.github.io). More testing appreciated. Future changes will be coming incrementally, not as a giant ball of code.

### CODE REVIEW

**Comment by qwertychouskie** [comment]
This sounds pretty nice!  Though I wonder if it would be beneficial to use a fork of https://github.com/supertuxkart/stk-addons for the server-side stuff, rather than re-inventing the wheel.  Using this for the server-side would enable adding a lot of cool features to Neverball, including:

- Online user accounts and account creation
- User uploads of addons
- Admins can mark addons as "Featured", which puts them at the top of the addons list
- User rating of addons
- Stats tracking of the addons, e.g. which are the most downloaded
- Stats tracking of the clients, e.g. which versions of Neverball are most used
- Friend system
- News ticker
- The boring but important "feature" of being well-tested in production with a semi-large player base

These features shouldn't be too hard to implement client-side, only really requiring an XML parser lib and some code to hook up the features in-game as necessary.  In the distant future, maybe Neverball could even implement a "Time Attack"-style multiplayer similar to what is used in e.g. Trackmania, I think it could be a lot of fun ;)

**Comment by parasti** [comment]
That's an awesome wishlist. It's a little out there. Now, what about this PR, does it work for you?

**Comment by qwertychouskie** [comment]
I downloaded and compiled, and it launched without errors, but I can't figure out where to download the level sets (maybe I'm just blind lol).

**Comment by parasti** [comment]
There should be 5 downloadable sets on the second page.

**Comment by qwertychouskie** [comment]
This is what it looks like on my end:
image

**Comment by qwertychouskie** [comment]
NVM, I just wasn't passing the flag to `make`, it's working now.

**Comment by parasti** [comment]
Yeah, sorry, I kind of hid that detail in a big blob of text, there.

Glad to hear it works. If you have any ideas for immediate UX improvements, feel free to share.

**Comment by qwertychouskie** [comment]
It seems to work quite well.  In the future I'd still love to see more scalability, (and maybe even support for addons ball types), but for now seems like an excellent start.  Only thing I'd change in this PR is to enable the functionality be default, instead of requiring a flag manually passed to `make`.

**Comment by parasti** [comment]
Downloadable balls would be quite easy, it's mostly just a matter of creating the UI for it. I was thinking, down the line, a more general "packages" (addons) screen, where all kinds of content could be downloaded and updated.

Also, GUI themes could be downloadable. Once they have an actual selection UI.

I think it makes sense to enable this by default, too. I added the flag just to be able to say that libcurl is "optional". It pulls in a lot of stuff.

**Comment by ersohnstyne** [comment]
Should be use within DLC?

**Pull request merged**
