### PR TITLE
Add support for Haiku

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
This fixes the build on Haiku for Neverball and Neverputt :) (shouldn't change anything for other OS's)

**Comment by ersohnstyne** [comment]
A fully Haiku supported? It should be have to work.

**Comment by Begasus** [comment]
@ersohnstyne I'm not sure I understand what you wrote (or meant) :) But yes, this works for the Haiku Operating System https://www.haiku-os.org/ :) Already posted links in the issue to show running Neverball and Neverputt.

**Comment by Begasus** [comment]
Thanks! :+1:

**Pull request merged**
