### PR TITLE
Reintroduce ZIP file support via miniz (single-file zlib/zip library)

### PR DESCRIPTION
**Pull request by parasti**

### CODE REVIEW

**Comment by ersohnstyne** [comment]
Aufgrund während der Regionalkongreß können nicht mehr mit der Source code synchronisieren.

**Comment by ersohnstyne** [comment]
Aufgrund während der Regionalkongreß können nicht mehr mit der Source code synchronisieren. Sie können nach wie vor die Antworten auf die häufig gestellten Fragen einsehen oder Kontakt mit uns aufnehmen aber es kann zu längeren Wartezeiten kommen als erwartet. Vielen Dank für Ihre Geduld.

**Comment by fwp** [comment]
Good to see ZIP file support without a dependency like PhysicsFS.

The new code didn't work out-of-the-box with my MinGW installation; it compiled but Neverball didn't list any zipped add-on levels. I traced this down to `mz_zip_reader_init_file_v2` failing with an `MZ_ZIP_FILE_SEEK_FAILED` error. Apparently, miniz' default use of `ftello64` and `fseeko64` clashes with the `-std=c99` compiler flag. As a workaround, I've changed it to `gnu99`, hoping there aren't any undesirable side effects.

**Comment by parasti** [comment]
Huh. That's strange because I developed this code on Windows with MinGW. I am running a MSYS2 setup with the mingw-w64 (gcc) compiler. Would love more info on this.

**Comment by fwp** [comment]
I'm using Eclipse CDT as a frontend for MinGW(32) with GCC 9.2.0-2, based on the latest(?) _mingw-get-setup.exe_ from mingw.org/osdn.net. MSYS isn't installed, and I'm not actually using the makefile. Instead, the linker is fed pre-built libraries that I cobbled together ages ago. Maps are compiled by running an extra script. This setup used to work, but it's entirely possible that there's a quirk somewhere.

With `-std=c99` set, the compiler complains about the lack of prototypes for `ftello64` and `fseeko64`. Is Mingw-w64 a requirement now?

**Comment by parasti** [comment]
So it's just missing declarations? But not really, because it works with a std flag? MinGW is weird. I just use MinGW-w64 because MinGW seemed very dead for a really long while. Contrary to the name, it's not 64-bit only, so I see no reason not to use it.

**Comment by fwp** [comment]
> So it's just missing declarations? But not really, because it works with a std flag?

What I think happens is that specifying `-std=c99` (which I do because the makefile does) implicitly defines `__STRICT_ANSI__`, causing `stdio.h` to omit declarations for the aforementioned functions. Then, when miniz calls `fseeko64` the arguments get mangled because the compiler doesn't know the exact types, and as a result the function fails with a return code of -1 (errno is `EINVAL`). Using `gnu99` solves all these problems.

I'll take a look at MinGW-w64 sometime.

**Pull request merged**
