### PR TITLE
Will checkpoints installing?

### PR DESCRIPTION
**Pull request by ersohnstyne**
I've been installed on my checkponts in 'mapc' and it was very long day to programming. Is that right?

### CODE REVIEW

**Comment by KodeBreaker-Has-SWAG** [comment]
I would love to see checkpoints in Neverball. It would be really good for extremely long levels. I could see some really creative ideas for this.

**Comment by ersohnstyne** [comment]
While the checkpoint light is still on and if the ball falls, it will return to the last position (including loads the collected coins and loads timer).

**Comment by ersohnstyne** [comment]
We'll waiting for compile, until should be work.

**Comment by ersohnstyne** [comment]
There we go, Msys2 works for the compiler again! (with Visual Studio)

**Comment by ersohnstyne** [comment]
I NEED WITH MICROSOFT TO STOP THIS!!!

**Pull request closed without merging**
