### PR TITLE
Add a material flag to enable lighting per material

### PR DESCRIPTION
**Pull request by parasti**
It's lit, yo.

### CODE REVIEW

**Comment by fwp** [comment]
Hey there,

one issue I have with porting this to Nuncabola is that it's not clear how to ensure existing SOLs are rendered properly. (That is, add-on levels, balls and backgrounds compiled with an earlier version of mapc and already installed on a user's computer.) It seems that one would have to identify whether a SOL is old or new, and in the former case apply some heuristics to guess which material should be lit and which shouldn't. The necessary code would probably negate the cleanliness gain offered by the new flag-based system, though.

Two more things:

* I assume *poof-green* being lit is not intentional?
* Should we care about keeping the flags in alphabetical order?

**Comment by parasti** [comment]
I attempted to script the material conversion, but it missed some instances, so I ended up doing some manual editing and just skimming over the diff. Seems like _poof-green_ isn't used by anything, so the script must not have picked it up as a billboard material.

Regarding backwards compatibility with existing SOLs, there's really two parts to that question.

One part is massaging the materials found in old SOLs to acquire the new flag. That should be fairly easy. All materials should acquire the lit flag, except billboard materials, and ... that's it, I guess? The rest of the affected materials are either in SOLs that we provide or they're hard-coded in the game, so they're already up to date. You could go the extra mile and write code to duplicate materials that are shared by billboards and other geometry and therefore need to be both lit and unlit, but I don't think those exist.

The other part is differentiating between old SOLs and new SOLs, which is difficult because the change didn't actually warrant a SOL version bump. 1.6.0 can read and display these files just fine. (I don't think it matters, but hey.) You could attempt to guess by activating the conversion path only for version 7 SOLs that have geoms but no lit materials..?

I didn't realize there was a particular order to these flags somewhere.

**Comment by parasti** [comment]
That detection idea actually doesn't make much sense, so maybe a version bump is the least painful option, who knows.

**Comment by fwp** [comment]
> Seems like *poof-green* isn't used by anything, so the script must not have picked it up as a billboard material.

Yeah, it's not used in any official maps. (Some add-on levels by Krabby Krap and ht-never reference it.)

> One part is massaging the materials found in old SOLs to acquire the new flag. That should be fairly easy. All materials should acquire the lit flag, except billboard materials, and ... that's it, I guess?

That may indeed be all that's needed. While it wouldn't work for the *geom* SOLs, it's unlikely anyone overrode any of those with custom versions.

> That detection idea actually doesn't make much sense, so maybe a version bump is the least painful option, who knows.

I tend to agree. Let's not run the risk of misidentifying a SOL (version) based on the contents. Level set authors who want to retain 1.6.0 compatibility could still distribute v7 SOLs for the time being.

> I didn't realize there was a particular order to these flags somewhere.

When rlk [introduced textual flags in material files](https://github.com/Neverball/neverball/commit/90b49870a9f8bafc45bd8f323499804974d9140f), those were initially in alphabetical order (and have mostly been kept that way since).

**Comment by fwp** [comment]
> Unlight mtrl/poof-green
> Bump SOL version to allow detection of pre-lit-flag SOLs
> Add lit flag to old SOL materials

Thanks for the changes. Nuncabola is now all lit up, too.

**Comment by rlk** [comment]
Good job, guys.

**Pull request merged**
