### PR TITLE
Update translations from Transifex

### PR DESCRIPTION
**Pull request by MiroslavR**
After executing (is this the way to do this or is there a script I am missing somewhere?)
> tx pull -l ca,de,el,eo,es,fi,fr,gd,gl,hu,it,ko,lv,nn,pl,pt_BR,ru,sk,sv,zh_CN,zh_TW

it looks like none of the other languages have been changed. Only sk has been added.

### CODE REVIEW

**Comment by parasti** [comment]
I haven't done this in ages, but from what I recall there's a command to get the added languages and a command to pull in updates for the existing ones. ("tx pull -l all" maybe? "tx help pull"? Something like that.) There should have been more new languages actually, according to this (and even more since then): http://forum.nevercorner.net/viewtopic.php?id=2871 Thanks for the effort, regardless.

**Comment by MiroslavR** [comment]
Oh, I thought only those languages defined in data/lang were to be pulled. Anyway, rebased to add the missing new languages.

**Comment by parasti** [comment]
Looks like this only has the new languages but no updates to existing ones? In that case it'd be better if the commit message said so.

**Comment by MiroslavR** [comment]
This should hopefully clear up any confusion that might arise.

**Pull request merged**
