### PR TITLE
Wiimote support for Windows 10 using WiiUse

### PR DESCRIPTION
**Pull request by nicolaschaufette**
supports holding the wiimote straight or sideways
let me know if you have any question

### CODE REVIEW

**Comment by parasti** [comment]
Hi! Your code seems very well integrated, it's a pleasure to read. I will try to merge it sometime this week.

**Comment by nicolaschaufette** [comment]
Hello,

Thanks !
I just added nunchuk support.

Regards
   Le lundi 11 mai 2020 à 09:20:16 UTC+2, Jānis Rūcis <notifications@github.com> a écrit :  
 
 


Hi! Your code seems very well integrated, it's a pleasure to read. I will try to merge it sometime this week.

**Comment by qwertychouskie** [comment]
Sounds cool!  The title mentions Windows 10, is there any particular reason why this wouldn't/couldn't work on Linux/MacOS too?

**Comment by nicolaschaufette** [comment]
No reason at all, I just didn't test. Maybe you may need to add the library bluetooth to the linker
Regards

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., mai 11, 2020 à 19:45, QwertyChouskie<notifications@github.com> a écrit :   


Sounds cool! The title mentions Windows 10, is there any particular reason why this wouldn't/couldn't work on Linux/MacOS too?

**Pull request merged**
