### PR TITLE
Resizable window + fullscreen toggle

### PR DESCRIPTION
**Pull request by parasti**
Fullscreen toggle is on the F11 key.

### CODE REVIEW

**Comment by ersohnstyne** [comment]
Should be used with resizeable as C++?

**Comment by ersohnstyne** [comment]
If you have an resizeable window and fullscreen toggle, then you don't need the resolution selection and fullscreen option in the graphic settings. Did you know?

**Comment by parasti** [comment]
I don't really think so. Fullscreen option is useful for game controllers and platforms without a keyboard. Resolution options are still useful for setting a standard window size.

**Comment by ersohnstyne** [comment]
In Mojang Studios, there is an UWP with graphic options using complex game configurations. **This is eventually required!**

**Comment by parasti** [comment]
I disagree. Neverball doesn't have near the configurational complexity that would call for a separate game launcher. Just because Minecraft has a launcher doesn't mean it's always a good idea.

**Comment by ersohnstyne** [comment]
This graphics options is not a launcher, but it can be high fidelity bedrock version, that were implemented to the game.

**Comment by parasti** [comment]
What you just said makes no sense.

**Comment by ersohnstyne** [comment]
This is not the bedrock version. Eventually I mean: Standard C++17?

**Comment by dos1** [comment]
@parasti Thanks, works like a charm on the Librem 5! Now when the game gets launched in portrait mode the user doesn't have to restart it in order to switch into landscape :)

**Comment by parasti** [comment]
Cool, good to hear!

**Pull request merged**
